
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-fundwave
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: johnstx/frontend-fw:1.1.0  # <-- Replace with your actual image + git hash
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
