apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-fundwave
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: 'https://github.com/Johnstx/Fintech-app.git'  
    targetRevision: HEAD  
    path: 'App/App-fundwave/frontend'
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  # Sync policy
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 