name: Docker Build and Push

on:
  push:
    branches:
        - main
        - workflow/*

jobs:
  Docker:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: johnstx
                password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Build and push Docker frontend image
            uses: docker/build-push-action@v6.13.0
            with:
                context: ./App/cicd/finmoney-app/frontend
                file:  ./App/cicd/finmoney-app/frontend/Dockerfile
                push: true
                tags: johnstx/frontend-fw:1.0.0

          - name: Build and push Docker backend image
            uses: docker/build-push-action@v6.13.0
            with:
                context: ./App/cicd/finmoney-app/backend
                file:  ./App/cicd/finmoney-app/backend/Dockerfile
                push: true
                tags: johnstx/backend-fw:1.0.0

          - name: Build and push Docker db image
            uses: docker/build-push-action@v6.13.0
            with:
                context: ./App/cicd/finmoney-app/database
                file:  ./App/cicd/finmoney-app/database/Dockerfile
                push: true
                tags: johnstx/db-fw:1.0.0
