
name: Terraform Infra CI/CD

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VERSION:  '1.6.6'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for deployment'
        required: true
        default: 'dev'
        # Add other environment options as desired

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./App/fundwave-eks-terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./App/fundwave-eks-terraform
 
      - name: Terraform Plan
        run: terraform plan -var-file=../../environments/${{ github.event.inputs.environment }}/values.tfvars -out=tfplan
        working-directory: ./App/fundwave-eks-terraform

      - name: Manual Approval
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.REPO_TOKEN }}
          issue-title: "Provisioning eks Infrastructure for ${{ github.event.inputs.environment }}"
          issue-body: "Kindly find details of infra & approve the provisioning of the EKS infrastructure for the ${{ github.event.inputs.environment }} environment."
          approvers: 'Johnstx'
          minimum-approvals: 1
          
      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        run: terraform apply tfplan
        working-directory: ./App/fundwave-eks-terraform