name: Terraform Destroy Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./App/fundwave-eks-terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./App/fundwave-eks-terraform

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=environments/${{ github.event.inputs.environment }}/values.tfvars -out=tfplan_destroy
        working-directory: ./App/fundwave-eks-terraform

      - name: Manual Approval for Destroy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.MANUAL_APPROVAL_TOKEN }}
          approvers: 'Johnstx'  
          minimum-approvals: 1
          issue-title: "Terraform Destroy Approval Required"
          issue-body: |
            A Terraform destroy is pending approval for environment `${{ github.event.inputs.environment }}`.
            Please review the plan and approve or deny.

      - name: Terraform Destroy
        run: terraform destroy -var-file=environments/${{ github.event.inputs.environment }}/values.tfvars -auto-approve
        working-directory: ./App/fundwave-eks-terraform
